### ISSUE TITLE
Pretty errors

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest-lite#205]
The ASGI server (FastAPI) underpinning FOREST-Lite produces a lot of traceback. I propose using https://pypi.org/project/pretty-errors/ to modify the traceback print, `import pretty_errors` and add it to `requirements.txt`?

**Comment by jwarner8** [comment]
Working on this 11/12/2020

**Comment by andrewgryan** [comment]
@jwarner8 is there a noticeable difference in the output when using `import pretty_errors` or is it unaffected? I think the docs say it doesn't work for all errors

**Comment by jwarner8** [comment]
Verbose appears the same whether its imported or not.

**Comment by andrewgryan** [comment]
@jwarner8 this is starting to look very complicated or not possible. We could revisit it at a later date but I think close it for now
